  name: Update Twitter Followers

  on:
    schedule:
      - cron: '0 * * * *'
    workflow_dispatch:

  jobs:
    update-followers:
      runs-on: ubuntu-latest

      steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update stats
        run: |
          echo '{"twitterFollowers":25,"tokenHolders":0,"marketCap":"$0","totalSupply":"1B"}' > data/stats.json

      - name: Commit changes
        run: |
          git config user.email "action@github.com"
          git config user.name "GitHub Action"
          git add data/stats.json
          git commit -m "Update stats" || exit 0
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
